CREATE DATABASE PROJETO

GO

USE PROJETO


CREATE TABLE CLIENTES (
	IDCLIENTE INT NOT NULL PRIMARY KEY IDENTITY,
	NOME VARCHAR(60)NOT NULL,
	CPF VARCHAR(14) NOT NULL
)

CREATE TABLE VENDEDORES (
  IDVENDEDOR INT NOT NULL PRIMARY KEY IDENTITY,
  NOME VARCHAR(60) NOT NULL,
  COMISAO DECIMAL(10,2) NOT NULL
)

CREATE TABLE FABRICANTES (
  IDFABRICANTE INT NOT NULL PRIMARY KEY IDENTITY,
  RAZAOSOCIAL VARCHAR(60) NOT NULL,
  TELEFONE VARCHAR(10) NOT NULL
)

CREATE TABLE PRODUTOS (
  IDPRODUTO INT NOT NULL PRIMARY KEY IDENTITY,
  DESCRICAO VARCHAR(60) NOT NULL,
  UNIDADE VARCHAR(5) NOT NULL,
  PRECOVENDA DECIMAL(10,2) NOT NULL,
  IDFABRICANTE INT NOT NULL FOREIGN KEY REFERENCES FABRICANTES(IDFABRICANTE) 
)

CREATE TABLE PEDIDOS (
  IDPEDIDO INT NOT NULL PRIMARY KEY IDENTITY,
  DTVENDA DATE NOT NULL,
  IDVENDEDOR INT NOT NULL FOREIGN KEY REFERENCES VENDEDORES(IDVENDEDOR) ,
  IDCLIENTE INT NOT NULL FOREIGN KEY REFERENCES CLIENTES(IDCLIENTE),
  SITUACAO CHAR(10) NOT NULL
)

CREATE TABLE PEDIDOPRODUTOS (
   IDPEDIDO INT NOT NULL FOREIGN KEY REFERENCES PEDIDOS(IDPEDIDO),
   IDPRODUTO INT NOT NULL  FOREIGN KEY REFERENCES PRODUTOS(IDPRODUTO),
   VALOR DECIMAL(10,2) NOT NULL,
   QUANTIDADE DECIMAL(10,3) NOT NULL
)

CREATE TABLE PAGAMENTOS (
   IDPAGAMENTO INT NOT NULL PRIMARY KEY IDENTITY,
   IDPEDIDO INT NOT NULL FOREIGN KEY REFERENCES PEDIDOS(IDPEDIDO),
   FORMAPAGAMENTO VARCHAR(15) NOT NULL,
   DTVENCIMENTO DATE NOT NULL,
   VALOR DECIMAL(10,2) NOT NULL,
   DTPAGAMENTO DATE NOT NULL,
   VALORPAGO DECIMAL(10,2) NOT NULL,
   SITUACAO VARCHAR(10) NOT NULL
)


